# Generated by Django 4.2.13 on 2024-07-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('rental_days', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField()),
                ('farmer_name', models.CharField(max_length=150)),
                ('farmer_contact', models.CharField(max_length=15)),
                ('owner_username', models.CharField(max_length=150)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='farmer.farmer')),
            ],
        ),
    ]
