# Generated by Django 4.2.13 on 2024-07-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        ('farmer', '0001_initial'),
        ('Machine_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='index.machine_details'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='Machine_owner.machineowner'),
        ),
    ]
