# Generated by Django 4.2.13 on 2024-07-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('cvv_number', models.CharField(max_length=4)),
                ('debit_card_number', models.CharField(max_length=16)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farmer.rentalrequest')),
            ],
        ),
    ]
