# Generated by Django 4.2.13 on 2024-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_remove_rentalrequest_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Completed', max_length=10),
        ),
    ]
