# Generated by Django 4.2.13 on 2024-07-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Machine_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_details',
            fields=[
                ('Machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Machine_Name', models.CharField(max_length=200)),
                ('Machine_type', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Days', models.CharField(max_length=200)),
                ('Machine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.ImageField(upload_to='uploads/')),
                ('Machine_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='Machine_owner.machineowner')),
            ],
        ),
    ]
