# Generated by Django 4.2.13 on 2024-07-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_details',
            name='Days',
        ),
    ]
